export const GET_DUNGEONS_ACHIEVEMENTS = "GET_DUNGEONS_ACHIEVEMENTS";
export const GET_DUNGEONS_ACHIEVEMENTS_FROM_API =
  "GET_DUNGEONS_ACHIEVEMENTS_FROM_API";
export const SET_LOADER = "SET_LOADER";
